### ISSUE TITLE
Specifying the index

### ISSUE THREAD

**Issue by russellseymour** [doctrine/search#115]
I know this is an old project and a prototype but I have been using it for my application with ElasticSearch and it is working __very__ well.  I am very pleased with it.

I would like to make is to that the Index can be specified by other means rather than in Annotations on the model.  I have looked at the code and seen that this creation is quite a long way along the code path.  Do you have any suggestions on the easiest way to pass in the index name as a variable rather than in the annotation?

I hope that makes sense.

Thanks, Russell

**Comment by MrHash** [comment]
Hi there is actually a yaml configuration implementation in the develop branch at https://github.com/doctrine/search/commit/3b93c8f16a6ad94a199500a0bdd88f1b3a86095a which you could use. It was done a while ago so can't remember if i provided implementation example. Let me know how you get on...

**Comment by MrHash** [comment]
Othewise if you have a clearer example of your requirement maybe I can advise..

**Comment by russellseymour** [comment]
@MrHash thanks for that.  I will have a look at the branch and see if I can use that implementation.  I will let you.

**Comment by MrHash** [comment]
OK, you always of the option of extending the annotation driver and implementing your own.

**Comment by russellseymour** [comment]
Thanks for the suggestions.  I do not think I can do what I want to do with the 'develop' branch or implementing an AnnotationDriver, but I maybe wrong.  This is what I am trying to do.

I am building an application that will be multi-tenancy.  I want to use the same structure of models for each tenant, but I want each tenant to have their own index in Elastic Search.  To do this I need to be able to set the index name via configuration and not hardcoded into the Annotation of the model.

I see this as being akin to being able to specify the database when using ORM in an RDBMS.

As far as I can tell there is no easy way to pass the name of the index to the ElasticSearch client without it being in the annotation.

**Comment by MrHash** [comment]
Well I think you have a couple of options. You can implement your own metadata driver and set on the configuration (https://github.com/doctrine/search/blob/master/demo/ElasticSearch.php#L25) which uses your own custom class meta data implementation (using Symfony expressions for example) so that you can programatically set the index, or alternatively i think you can use the yaml driver, but specify a different yaml directory for each tenant, where the config extends a common shared parent so you don't need to duplicate config. Or you could extend the yaml driver also https://github.com/doctrine/search/blob/develop/lib/Doctrine/Search/Mapping/Driver/YamlDriver.php#L133

**Comment by russellseymour** [comment]
OK brilliant thanks for you help.  I will look into those.
Hope you do not mind if I contact you again if I get stuck - this has been very helpful.
