### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by JCMais** [doctrine/search#122]
Hi, is that project still supported?

If yes, any plans to release a production version?

**Comment by MrHash** [comment]
We discussed this a bit in #116 - the project is not in active development, and is missing tests and so on so it's not really in a releasable state, but with a bit of work it could be released.

**Comment by Zyqsempai** [comment]
@MrHash I agree with you, i think that project have the feature and can be released. But since project was developed many things changed, ElasticSearch now at 5.x version, so we need to rewrite many things, and write many-many test. I will be glad to help here, what do you think, may be you have some suggestions or plans?

**Comment by Zyqsempai** [comment]
In my opinion first of all we need to dockerize project, add ElasticSerach container (or other client libraries) and write good functional tests, https://github.com/doctrine/search/issues/85 implement this logic, and i  also faced memory leak on the big amount of data, so i want to fix it to. This is what i can do in first steps.

**Comment by MrHash** [comment]
i'm closing this for now since it looks like we are ready to start working on some features. please review the updates in the 0.2 branch to see a whole load of work i did before which could be constructive.
